INSERT INTO Authors (Name, Surname)
VALUES
    ('J.K.', 'Rowling'),
    ('Stephen', 'King'),
    ('George R.R.', 'Martin'),
    ('J.R.R.', 'Tolkien'),
    ('Agatha', 'Christie'),
    ('Dan', 'Brown'),
    ('Jane', 'Austen'),
    ('Mark', 'Twain'),
    ('Ernest', 'Hemingway'),
    ('Leo', 'Tolstoy'),
    ('F. Scott', 'Fitzgerald'),
    ('Oscar', 'Wilde'),
    ('Gabriel', 'García Márquez'),
    ('Haruki', 'Murakami'),
    ('Virginia', 'Woolf'),
    ('Herman', 'Melville'),
    ('Toni', 'Morrison'),
    ('Margaret', 'Atwood'),
    ('Philip', 'Pullman'),
    ('Terry', 'Pratchett'),
    ('Joanne', 'Harris'),
    ('John', 'Grisham'),
    ('Jodi', 'Picoult'),
    ('Neil', 'Gaiman'),
    ('Kazuo', 'Ishiguro'),
    ('Orhan', 'Pamuk'),
    ('Maya', 'Angelou'),
    ('Salman', 'Rushdie'),
    ('Gillian', 'Flynn'),
    ('Alice', 'Walker'),
    ('H.P.', 'Lovecraft'),
    ('Isaac', 'Asimov'),
    ('Ray', 'Bradbury'),
    ('C.S.', 'Lewis'),
    ('Ayn', 'Rand'),
    ('Erich', 'Maria Remarque'),
    ('Khaled', 'Hosseini'),
    ('J.D.', 'Salinger'),
    ('Roxane', 'Gay'),
    ('Margaret', 'Weis'),
    ('Tracy', 'Hickman'),
    ('Gillian', 'Flynn'),
    ('Elena', 'Ferrante'),
    ('Chimamanda Ngozi', 'Adichie'),
    ('Bram', 'Stoker')
;