
INSERT INTO Genres(Name) VALUES
    ('Fantasy'),
    ('Science Fiction'),
    ('Mystery/Thriller'),
    ('Romance'),
    ('Historical Fiction'),
    ('Contemporary Fiction'),
    ('Literary Fiction'),
    ('Adventure'),
    ('Biography/Memoir'),
    ('Self-Help'),
    ('Health/Fitness'),
    ('History'),
    ('Science'),
    ('Technology'),
    ('Psychology'),
    ('Cooking/Food'),
    ('Travel'),
    ('Philosophy'),
    ('Picture Books'),
    ('Early Readers'),
    ('Middle-Grade Fiction'),
    ('Mathematics'),
    ('Science'),
    ('Social Sciences'),
    ('Literature'),
    ('History'),
    ('Art'),
    ('Business/Economics'),
    ('Christianity'),
    ('Islam'),
    ('Buddhism'),
    ('Hinduism'),
    ('New Age/Spirituality'),
    ('Graphic Novels/Comics'),
    ('Poetry'),
    ('Anthologies/Short Stories'),
    ('Classic Literature'),
    ('Art/Photography'),
    ('Music');